fix: POSIX smoke tests
This fixes the following errors on machines with glibc >= 2.43 because strstr
now returns a const char *.

```
src/core/utils.c:567:17: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
    567 |     char *ptr = strchr(boundary, '*');
        |                 ^~~~~~
src/core/utils.c:589:9: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
    589 |     ptr = strchr(boundary, '*');
        |         ^
cc1: all warnings being treated as errors
```

Ticket: None
Changelog: None

Signed-off-by: Adam Duskett <aduskett@gmail.com>